default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: dvt_residential_sales_development

test:
  <<: *default
  database: dvt_residential_sales_test

production:
  <<: *default
  database: dvt_residential_sales_production
